name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20 LTS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build
        env:
          # Lazım olsa müvəqqəti diaqnostika üçün bunları 1 edə bilərsən:
          # NEXT_DISABLE_ESLINT: "1"
          # NEXT_DISABLE_TSC_CHECK: "1"
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm run build